---
- name: Stat to check whether /root/.my.cnf exists
  ansible.builtin.stat:
    path: /root/.my.cnf
  register: __cnf_file

- name: Set Percona XtraDB root password
  block:

    - name: Get temporary root password
      ansible.builtin.shell: >-
        grep 'temporary password' /var/log/mysqld.log |
        awk '{print $NF}' | tail -n 1
      register: __percona_root_temp_password
      no_log: "{{ percona_no_log }}"
      changed_when: __percona_root_temp_password.rc != 0 

    - name: Create .mycnf file for root user
      ansible.builtin.copy:
        dest: "/root/.my.cnf"
        mode: 0644
        content: |
          [client]
          user={{ percona_root_user | quote }}
          password={{ __percona_root_temp_password.stdout | quote }}

    - name: Set new root password
      ansible.builtin.shell: >-
        mysql --connect-expired-password -e 
        "ALTER USER '{{ percona_root_user }}'@'localhost' 
        IDENTIFIED WITH mysql_native_password BY '{{ percona_root_password }}';"
      register: __percona_change_root_password
      changed_when: false
      failed_when: false

    - name: Change root password in cnf file
      ansible.builtin.lineinfile:
        path: "/root/.my.cnf"
        state: present
        regexp: '^.?password=*'
        line: "password={{ percona_root_password | quote }}"

  when: 
    - not __cnf_file.stat.exists