---
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test-cluster-01 
    image: "bmeme/docker-ansible-${MOLECULE_DISTRO:-rockylinux:9.4-2.15}"
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
  - name: test-cluster-02 
    image: "bmeme/docker-ansible-${MOLECULE_DISTRO:-rockylinux:9.4-2.15}"
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
  - name: test-cluster-03 
    image: "bmeme/docker-ansible-${MOLECULE_DISTRO:-rockylinux:9.4-2.15}"
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}:${HOME}/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles"
  inventory:
    host_vars:
      localhost:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
  log: true
  lint:
    name: ansible-lint
    enabled: true
verifier:
  name: ansible